// Created by Credix - Licence: https://creativecommons.org/licenses/by-nc-sa/4.0/ 
#ifndef SETTINGS_H
#define SETTINGS_H

#include <string>

float nightmode1;
float nightmode2;
float nightmode3;

enum ESPBoxType_t {
	ESPBOX_NONE = 0,
	ESPBOX_DEFAULT = 1,
	ESPBOX_CORNERED = 2,
	ESPBOX_VERTICALLINE = 3,
	ESPBOX_HORIZONTALLINE = 4,
	ESPBOX_LINES = 5
};

enum AntiAimType_t {
	ANTIAIM_NONE = -1,
	ANTIAIM_SLOW_SPIN = 0,
	ANTIAIM_RANDOM_SPIN = 1,
	ANTIAIM_YAW_DOWN = 2,
	ANTIAIM_YAW_RANDOM = 3
};

enum SilentAimType_t {
	SILENTAIM_NONE = -1,
	SILENTAIM_CLOSEST_TO_BASE = 0,
	SILENTAIM_CLOSEST_TO_CROSSHAIR = 1
};

enum KnifeType_t {
	KNIFE_DEFAULT_T = 1,
	KNIFE_DEFAULT_CT = 2,
	KNIFE_BAYONET,
	KNIFE_FLIP,
	KNIFE_GUT,
	KNIFE_KARAM,
	KNIFE_M9_BAY,
	KNIFE_TACTICAL,
	KNIFE_FALCHION_ADVANCED,
	KNIFE_SURVIVAL_BOWIE,
	KNIFE_BUTTERFLY,
	KNIFE_PUSH,
	KNIFE_WIDOWMAKER,
	KNIFE_URSUS,
	KNIFE_STILETTO,
	KNIFE_GYPSY_JACKKNIFE
};

int KnifeDefinitions_t[] {
	41,
	59,
	42,
	500,
	505,
	506,
	507,
	508,
	509,
	512,
	514,
	515,
	516,
	523,
	519,
	522,
	520
};

std::string KnifeModels[] = {
	"models/weapons/v_knife_default.mdl",
	"models/weapons/v_knife_default_t.mdl",
	"models/weapons/v_knife_default_ct.mdl",
	"models/weapons/v_knife_bayonet.mdl",
	"models/weapons/v_knife_flip.mdl",
	"models/weapons/v_knife_gut.mdl",
	"models/weapons/v_knife_karam.mdl",
	"models/weapons/v_knife_m9_bay.mdl",
	"models/weapons/v_knife_tactical.mdl",
	"models/weapons/v_knife_falchion_advanced.mdl",
	"models/weapons/v_knife_survival_bowie.mdl",
	"models/weapons/v_knife_butterfly.mdl",
	"models/weapons/v_knife_push.mdl",
	"models/weapons/v_knife_widowmaker.mdl",
	"models/weapons/v_knife_ursus.mdl",
	"models/weapons/v_knife_stiletto.mdl",
	"models/weapons/v_knife_gypsy_jackknife.mdl"
};

enum ChamMaterials_t {
	MATERIAL_NONE = 0,
	MATERIAL_LIT = 1,
	MATERIAL_UNLIT = 2,
	MATERIAL_METALIC = 3
};

enum ESPHealthBarType_t {
	HEALTHBAR_NONE = 0,
	HEALTHBAR_BAR = 1,
	HEALTHBAR_TEXT = 2
};

/* EntityQuality, ItemDefinitionIndex and PaintKit enum by https://github.com/michel-pi/csgo-items-parser */
enum EntityQuality
{
	NORMAL = 0,
	GENUINE = 1,
	VINTAGE = 2,
	UNUSUAL = 3,
	UNIQUE = 4,
	COMMUNITY = 5,
	DEVELOPER = 6,
	SELFMADE = 7,
	CUSTOMIZED = 8,
	STRANGE = 9,
	COMPLETED = 10,
	HAUNTED = 11,
	TOURNAMENT = 12,
};
enum ItemDefinitionIndex : short int
{
	WEAPON_DEAGLE = 1,
	WEAPON_ELITE = 2,
	WEAPON_FIVESEVEN = 3,
	WEAPON_GLOCK = 4,
	WEAPON_AK47 = 7,
	WEAPON_AUG = 8,
	WEAPON_AWP = 9,
	WEAPON_FAMAS = 10,
	WEAPON_G3SG1 = 11,
	WEAPON_GALILAR = 13,
	WEAPON_M249 = 14,
	WEAPON_M4A1 = 16,
	WEAPON_MAC10 = 17,
	WEAPON_P90 = 19,
	WEAPON_MP5SD = 23,
	WEAPON_UMP45 = 24,
	WEAPON_XM1014 = 25,
	WEAPON_BIZON = 26,
	WEAPON_MAG7 = 27,
	WEAPON_NEGEV = 28,
	WEAPON_SAWEDOFF = 29,
	WEAPON_TEC9 = 30,
	WEAPON_TASER = 31,
	WEAPON_HKP2000 = 32,
	WEAPON_MP7 = 33,
	WEAPON_MP9 = 34,
	WEAPON_NOVA = 35,
	WEAPON_P250 = 36,
	WEAPON_SCAR20 = 38,
	WEAPON_SG556 = 39,
	WEAPON_SSG08 = 40,
	WEAPON_KNIFEGG = 41,
	WEAPON_KNIFE = 42,
	WEAPON_FLASHBANG = 43,
	WEAPON_HEGRENADE = 44,
	WEAPON_SMOKEGRENADE = 45,
	WEAPON_MOLOTOV = 46,
	WEAPON_DECOY = 47,
	WEAPON_INCGRENADE = 48,
	WEAPON_C4 = 49,
	ITEM_KEVLAR = 50,
	ITEM_ASSAULTSUIT = 51,
	ITEM_HEAVYASSAULTSUIT = 52,
	ITEM_NVG = 54,
	ITEM_DEFUSER = 55,
	ITEM_CUTTERS = 56,
	WEAPON_HEALTHSHOT = 57,
	MUSICKIT_DEFAULT = 58,
	WEAPON_KNIFE_T = 59,
	WEAPON_M4A1_SILENCER = 60,
	WEAPON_USP_SILENCER = 61,
	WEAPON_CZ75A = 63,
	WEAPON_REVOLVER = 64,
	WEAPON_TAGRENADE = 68,
	WEAPON_FISTS = 69,
	WEAPON_BREACHCHARGE = 70,
	WEAPON_TABLET = 72,
	WEAPON_MELEE = 74,
	WEAPON_AXE = 75,
	WEAPON_HAMMER = 76,
	WEAPON_SPANNER = 78,
	WEAPON_KNIFE_GHOST = 80,
	WEAPON_FIREBOMB = 81,
	WEAPON_DIVERSION = 82,
	WEAPON_FRAG_GRENADE = 83,
	WEAPON_SNOWBALL = 84,
	WEAPON_BAYONET = 500,
	WEAPON_KNIFE_FLIP = 505,
	WEAPON_KNIFE_GUT = 506,
	WEAPON_KNIFE_KARAMBIT = 507,
	WEAPON_KNIFE_M9_BAYONET = 508,
	WEAPON_KNIFE_TACTICAL = 509,
	WEAPON_KNIFE_FALCHION = 512,
	WEAPON_KNIFE_SURVIVAL_BOWIE = 514,
	WEAPON_KNIFE_BUTTERFLY = 515,
	WEAPON_KNIFE_PUSH = 516,
	WEAPON_KNIFE_URSUS = 519,
	WEAPON_KNIFE_GYPSY_JACKKNIFE = 520,
	WEAPON_KNIFE_STILETTO = 522,
	WEAPON_KNIFE_WIDOWMAKER = 523,
	MUSICKIT = 1314,
	STUDDED_BLOODHOUND_GLOVES = 5027,
	T_GLOVES = 5028,
	CT_GLOVES = 5029,
	SPORTY_GLOVES = 5030,
	SLICK_GLOVES = 5031,
	LEATHER_HANDWRAPS = 5032,
	MOTORCYCLE_GLOVES = 5033,
	SPECIALIST_GLOVES = 5034,
	STUDDED_HYDRA_GLOVES = 5035,
};
enum PaintKit
{
	DEFAULT = 0,
	GROUNDWATER = 2,
	CANDY_APPLE = 3,
	FOREST_DDPAT = 5,
	ARCTIC_CAMO = 6,
	DESERT_STORM = 8,
	BENGAL_TIGER = 9,
	COPPERHEAD = 10,
	SKULLS = 11,
	CRIMSON_WEB = 12,
	BLUE_STREAK = 13,
	RED_LAMINATE = 14,
	GUNSMOKE = 15,
	JUNGLE_TIGER = 16,
	URBAN_DDPAT = 17,
	VIRUS = 20,
	GRANITE_MARBLEIZED = 21,
	CONTRAST_SPRAY = 22,
	FOREST_LEAVES = 25,
	LICHEN_DASHED = 26,
	BONE_MASK = 27,
	ANODIZED_NAVY = 28,
	SNAKE_CAMO = 30,
	SILVER = 32,
	HOT_ROD = 33,
	METALLIC_DDPAT = 34,
	OSSIFIED = 36,
	BLAZE = 37,
	FADE = 38,
	BULLDOZER = 39,
	NIGHT = 40,
	COPPER = 41,
	BLUE_STEEL = 42,
	STAINED = 43,
	CASE_HARDENED = 44,
	CONTRACTOR = 46,
	COLONY = 47,
	DRAGON_TATTOO = 48,
	LIGHTNING_STRIKE = 51,
	SLAUGHTER = 59,
	DARK_WATER = 60,
	HYPNOTIC = 61,
	BLOOMSTICK = 62,
	COLD_BLOODED = 67,
	CARBON_FIBER = 70,
	SCORPION = 71,
	SAFARI_MESH = 72,
	WINGS = 73,
	POLAR_CAMO = 74,
	BLIZZARD_MARBLEIZED = 75,
	WINTER_FOREST = 76,
	BOREAL_FOREST = 77,
	FOREST_NIGHT = 78,
	ORANGE_DDPAT = 83,
	PINK_DDPAT = 84,
	MUDDER = 90,
	CYANOSPATTER = 92,
	CARAMEL = 93,
	GRASSLAND = 95,
	BLUE_SPRUCE = 96,
	ULTRAVIOLET = 98,
	SAND_DUNE = 99,
	STORM = 100,
	TORNADO = 101,
	WHITEOUT = 102,
	GRASSLAND_LEAVES = 104,
	POLAR_MESH = 107,
	CONDEMNED = 110,
	GLACIER_MESH = 111,
	SAND_MESH = 116,
	SAGE_SPRAY = 119,
	JUNGLE_SPRAY = 122,
	SAND_SPRAY = 124,
	URBAN_PERFORATED = 135,
	WAVES_PERFORATED = 136,
	ORANGE_PEEL = 141,
	URBAN_MASKED = 143,
	JUNGLE_DASHED = 147,
	SAND_DASHED = 148,
	URBAN_DASHED = 149,
	JUNGLE = 151,
	DEMOLITION = 153,
	AFTERIMAGE = 154,
	BULLET_RAIN = 155,
	DEATH_BY_KITTY = 156,
	PALM = 157,
	WALNUT = 158,
	BRASS = 159,
	SPLASH = 162,
	MODERN_HUNTER = 164,
	SPLASH_JAM = 165,
	BLAZE_ORANGE = 166,
	RADIATION_HAZARD = 167,
	NUCLEAR_THREAT = 168,
	FALLOUT_WARNING = 169,
	PREDATOR = 170,
	IRRADIATED_ALERT = 171,
	BLACK_LAMINATE = 172,
	BOOM = 174,
	SCORCHED = 175,
	FADED_ZEBRA = 176,
	MEMENTO = 177,
	DOOMKITTY = 178,
	NUCLEAR_THREAT2 = 179,
	FIRE_SERPENT = 180,
	CORTICERA = 181,
	EMERALD_DRAGON = 182,
	OVERGROWTH = 183,
	CORTICERA2 = 184,
	GOLDEN_KOI = 185,
	WAVE_SPRAY = 186,
	ZIRKA = 187,
	GRAVEN = 188,
	BRIGHT_WATER = 189,
	BLACK_LIMBA = 190,
	TEMPEST = 191,
	SHATTERED = 192,
	BONE_PILE = 193,
	SPITFIRE = 194,
	DEMETER = 195,
	EMERALD = 196,
	ANODIZED_NAVY2 = 197,
	HAZARD = 198,
	DRY_SEASON = 199,
	MAYAN_DREAMS = 200,
	PALM2 = 201,
	JUNGLE_DDPAT = 202,
	RUST_COAT = 203,
	MOSAICO = 204,
	JUNGLE2 = 205,
	TORNADO2 = 206,
	FACETS = 207,
	SAND_DUNE2 = 208,
	GROUNDWATER2 = 209,
	ANODIZED_GUNMETAL = 210,
	OCEAN_FOAM = 211,
	GRAPHITE = 212,
	OCEAN_FOAM2 = 213,
	GRAPHITE2 = 214,
	X_RAY = 215,
	BLUE_TITANIUM = 216,
	BLOOD_TIGER = 217,
	HEXANE = 218,
	HIVE = 219,
	HEMOGLOBIN = 220,
	SERUM = 221,
	BLOOD_IN_THE_WATER = 222,
	NIGHTSHADE = 223,
	WATER_SIGIL = 224,
	GHOST_CAMO = 225,
	BLUE_LAMINATE = 226,
	ELECTRIC_HIVE = 227,
	BLIND_SPOT = 228,
	AZURE_ZEBRA = 229,
	STEEL_DISRUPTION = 230,
	COBALT_DISRUPTION = 231,
	CRIMSON_WEB2 = 232,
	TROPICAL_STORM = 233,
	ASH_WOOD = 234,
	VARICAMO = 235,
	NIGHT_OPS = 236,
	URBAN_RUBBLE = 237,
	VARICAMO_BLUE = 238,
	CALICAMO = 240,
	HUNTING_BLIND = 241,
	ARMY_MESH = 242,
	GATOR_MESH = 243,
	TEARDOWN = 244,
	ARMY_RECON = 245,
	AMBER_FADE = 246,
	DAMASCUS_STEEL = 247,
	RED_QUARTZ = 248,
	COBALT_QUARTZ = 249,
	FULL_STOP = 250,
	PIT_VIPER = 251,
	SILVER_QUARTZ = 252,
	ACID_FADE = 253,
	NITRO = 254,
	ASIIMOV = 255,
	THE_KRAKEN = 256,
	GUARDIAN = 257,
	MEHNDI = 258,
	REDLINE = 259,
	PULSE = 260,
	MARINA = 261,
	ROSE_IRON = 262,
	RISING_SKULL = 263,
	SANDSTORM = 264,
	KAMI = 265,
	MAGMA = 266,
	COBALT_HALFTONE = 267,
	TREAD_PLATE = 268,
	THE_FUSCHIA_IS_NOW = 269,
	VICTORIA = 270,
	UNDERTOW = 271,
	TITANIUM_BIT = 272,
	HEIRLOOM = 273,
	COPPER_GALAXY = 274,
	RED_FRAGCAM = 275,
	PANTHER = 276,
	STAINLESS = 277,
	BLUE_FISSURE = 278,
	ASIIMOV2 = 279,
	CHAMELEON = 280,
	CORPORAL = 281,
	REDLINE2 = 282,
	TRIGON = 283,
	HEAT = 284,
	TERRAIN = 285,
	ANTIQUE = 286,
	PULSE2 = 287,
	SERGEANT = 288,
	SANDSTORM2 = 289,
	GUARDIAN2 = 290,
	HEAVEN_GUARD = 291,
	DEATH_RATTLE = 293,
	GREEN_APPLE = 294,
	FRANKLIN = 295,
	METEORITE = 296,
	TUXEDO = 297,
	ARMY_SHEEN = 298,
	CAGED_STEEL = 299,
	EMERALD_PINSTRIPE = 300,
	ATOMIC_ALLOY = 301,
	VULCAN = 302,
	ISAAC = 303,
	SLASHED = 304,
	TORQUE = 305,
	ANTIQUE2 = 306,
	RETRIBUTION = 307,
	KAMI2 = 308,
	HOWL = 309,
	CURSE = 310,
	DESERT_WARFARE = 311,
	CYREX = 312,
	ORION = 313,
	HEAVEN_GUARD2 = 314,
	POISON_DART = 315,
	JAGUAR = 316,
	BRATATAT = 317,
	ROAD_RASH = 318,
	DETOUR = 319,
	RED_PYTHON = 320,
	MASTER_PIECE = 321,
	NITRO2 = 322,
	RUST_COAT2 = 323,
	CHALICE = 325,
	KNIGHT = 326,
	CHAINMAIL = 327,
	HAND_CANNON = 328,
	DARK_AGE = 329,
	BRIAR = 330,
	ROYAL_BLUE = 332,
	INDIGO = 333,
	TWIST = 334,
	MODULE = 335,
	DESERT_STRIKE = 336,
	TATTER = 337,
	PULSE3 = 338,
	CAIMAN = 339,
	JET_SET = 340,
	FIRST_CLASS = 341,
	LEATHER = 342,
	COMMUTER = 343,
	DRAGON_LORE = 344,
	FIRST_CLASS2 = 345,
	COACH_CLASS = 346,
	PILOT = 347,
	RED_LEATHER = 348,
	OSIRIS = 349,
	TIGRIS = 350,
	CONSPIRACY = 351,
	FOWL_PLAY = 352,
	WATER_ELEMENTAL = 353,
	URBAN_HAZARD = 354,
	DESERT_STRIKE2 = 355,
	KOI = 356,
	IVORY = 357,
	SUPERNOVA = 358,
	ASIIMOV3 = 359,
	CYREX2 = 360,
	ABYSS = 361,
	LABYRINTH = 362,
	TRAVELER = 363,
	BUSINESS_CLASS = 364,
	OLIVE_PLAID = 365,
	GREEN_PLAID = 366,
	REACTOR = 367,
	SETTING_SUN = 368,
	NUCLEAR_WASTE = 369,
	BONE_MACHINE = 370,
	STYX = 371,
	NUCLEAR_GARDEN = 372,
	CONTAMINATION = 373,
	TOXIC = 374,
	RADIATION_HAZARD2 = 375,
	CHEMICAL_GREEN = 376,
	HOT_SHOT = 377,
	FALLOUT_WARNING2 = 378,
	CERBERUS = 379,
	WASTELAND_REBEL = 380,
	GRINDER = 381,
	MURKY = 382,
	BASILISK = 383,
	GRIFFIN = 384,
	FIRESTARTER = 385,
	DART = 386,
	URBAN_HAZARD2 = 387,
	CARTEL = 388,
	FIRE_ELEMENTAL = 389,
	HIGHWAYMAN = 390,
	CARDIAC = 391,
	DELUSION = 392,
	TRANQUILITY = 393,
	CARTEL2 = 394,
	MAN_O_WAR = 395,
	URBAN_SHOCK = 396,
	NAGA = 397,
	CHATTERBOX = 398,
	CATACOMBS = 399,
	DRAGON_KING = 400,
	SYSTEM_LOCK = 401,
	MALACHITE = 402,
	DEADLY_POISON = 403,
	MUERTOS = 404,
	SERENITY = 405,
	GROTTO = 406,
	QUICKSILVER = 407,
	TIGER_TOOTH = 409,
	DAMASCUS_STEEL2 = 410,
	DAMASCUS_STEEL3 = 411,
	MARBLE_FADE = 413,
	RUST_COAT3 = 414,
	DOPPLER = 415,
	DOPPLER2 = 416,
	DOPPLER3 = 417,
	DOPPLER4 = 418,
	DOPPLER5 = 419,
	DOPPLER6 = 420,
	DOPPLER7 = 421,
	ELITE_BUILD = 422,
	ARMOR_CORE = 423,
	WORM_GOD = 424,
	BRONZE_DECO = 425,
	VALENCE = 426,
	MONKEY_BUSINESS = 427,
	ECO = 428,
	DJINN = 429,
	HYPER_BEAST = 430,
	HEAT2 = 431,
	MAN_O_WAR2 = 432,
	NEON_RIDER = 433,
	ORIGAMI = 434,
	POLE_POSITION = 435,
	GRAND_PRIX = 436,
	TWILIGHT_GALAXY = 437,
	CHRONOS = 438,
	HADES = 439,
	ICARUS_FELL = 440,
	MINOTAURS_LABYRINTH = 441,
	ASTERION = 442,
	PATHFINDER = 443,
	DAEDALUS = 444,
	HOT_ROD2 = 445,
	MEDUSA = 446,
	DUELIST = 447,
	PANDORAS_BOX = 448,
	POSEIDON = 449,
	MOON_IN_LIBRA = 450,
	SUN_IN_LEO = 451,
	SHIPPING_FORECAST = 452,
	EMERALD2 = 453,
	PARA_GREEN = 454,
	AKIHABARA_ACCEPT = 455,
	HYDROPONIC = 456,
	BAMBOO_PRINT = 457,
	BAMBOO_SHADOW = 458,
	BAMBOO_FOREST = 459,
	AQUA_TERRACE = 460,
	COUNTER_TERRACE = 462,
	TERRACE = 463,
	NEON_KIMONO = 464,
	ORANGE_KIMONO = 465,
	CRIMSON_KIMONO = 466,
	MINT_KIMONO = 467,
	MIDNIGHT_STORM = 468,
	SUNSET_STORM = 469,
	SUNSET_STORM2 = 470,
	DAYBREAK = 471,
	IMPACT_DRILL = 472,
	SEABIRD = 473,
	AQUAMARINE_REVENGE = 474,
	HYPER_BEAST2 = 475,
	YELLOW_JACKET = 476,
	NEURAL_NET = 477,
	ROCKET_POP = 478,
	BUNSEN_BURNER = 479,
	EVIL_DAIMYO = 480,
	NEMESIS = 481,
	RUBY_POISON_DART = 482,
	LOUDMOUTH = 483,
	RANGER = 484,
	HANDGUN = 485,
	ELITE_BUILD2 = 486,
	CYREX3 = 487,
	RIOT = 488,
	TORQUE2 = 489,
	FRONTSIDE_MISTY = 490,
	DUALING_DRAGONS = 491,
	SURVIVOR_Z = 492,
	FLUX = 493,
	STONE_COLD = 494,
	WRAITHS = 495,
	NEBULA_CRUSADER = 496,
	GOLDEN_COIL = 497,
	RANGEEN = 498,
	COBALT_CORE = 499,
	SPECIAL_DELIVERY = 500,
	WINGSHOT = 501,
	GREEN_MARINE = 502,
	BIG_IRON = 503,
	KILL_CONFIRMED = 504,
	SCUMBRIA = 505,
	POINT_DISARRAY = 506,
	RICOCHET = 507,
	FUEL_ROD = 508,
	CORINTHIAN = 509,
	RETROBUTION = 510,
	THE_EXECUTIONER = 511,
	ROYAL_PALADIN = 512,
	POWER_LOADER = 514,
	IMPERIAL = 515,
	SHAPEWOOD = 516,
	YORICK = 517,
	OUTBREAK = 518,
	TIGER_MOTH = 519,
	AVALANCHE = 520,
	TECLU_BURNER = 521,
	FADE2 = 522,
	AMBER_FADE2 = 523,
	FUEL_INJECTOR = 524,
	ELITE_BUILD3 = 525,
	PHOTIC_ZONE = 526,
	KUMICHO_DRAGON = 527,
	CARTEL3 = 528,
	VALENCE2 = 529,
	TRIUMVIRATE = 530,
	ROYAL_LEGION = 532,
	THE_BATTLESTAR = 533,
	LAPIS_GATOR = 534,
	PRAETORIAN = 535,
	IMPIRE = 536,
	HYPER_BEAST3 = 537,
	NECROPOS = 538,
	JAMBIYA = 539,
	LEAD_CONDUIT = 540,
	DOPPLER8 = 617,
	DOPPLER9 = 618,
	DOPPLER10 = 619,
	ULTRAVIOLET2 = 620,
	ULTRAVIOLET3 = 621,
	CHARRED = 10006,
	SNAKEBITE = 10007,
	BRONZED = 10008,
	LEATHER2 = 10009,
	SPRUCE_DDPAT = 10010,
	LUNAR_WEAVE = 10013,
	CONVOY = 10015,
	CRIMSON_WEAVE = 10016,
	SUPERCONDUCTOR = 10018,
	ARID = 10019,
	SLAUGHTER2 = 10021,
	ECLIPSE = 10024,
	SPEARMINT = 10026,
	BOOM2 = 10027,
	COOL_MINT = 10028,
	FOREST_DDPAT2 = 10030,
	CRIMSON_KIMONO2 = 10033,
	EMERALD_WEB = 10034,
	FOUNDATION = 10035,
	BADLANDS = 10036,
	PANDORAS_BOX2 = 10037,
	HEDGE_MAZE = 10038,
	GUERRILLA = 10039,
	DIAMONDBACK = 10040,
	KING_SNAKE = 10041,
	IMPERIAL_PLAID = 10042,
	OVERTAKE = 10043,
	RACING_GREEN = 10044,
	AMPHIBIOUS = 10045,
	BRONZE_MORPH = 10046,
	OMEGA = 10047,
	VICE = 10048,
	POW = 10049,
	TURTLE = 10050,
	TRANSPORT = 10051,
	POLYGON = 10052,
	COBALT_SKULLS = 10053,
	OVERPRINT = 10054,
	DUCT_TAPE = 10055,
	ARBOREAL = 10056,
	EMERALD3 = 10057,
	MANGROVE = 10058,
	RATTLER = 10059,
	CASE_HARDENED2 = 10060,
	CRIMSON_WEB3 = 10061,
	BUCKSHOT = 10062,
	FADE3 = 10063,
	MOGUL = 10064,
	FACILITY_SKETCH = 775,
	FACILITY_NEGATIVE = 776,
	FACILITY_DRAFT = 777,
	FACILITY_DARK = 778,
	RANDOM_ACCESS = 779,
	MAINFRAME = 780,
	CO_PROCESSOR = 781,
	MOTHERBOARD = 782,
	BULKHEAD = 783,
	COOLANT = 784,
	MANDREL = 785,
	EXCHANGER = 786,
	CORE_BREACH = 787,
	ACHERON = 788,
	NUCLEAR_GARDEN3 = 789,
	COLD_FUSION = 790,
	REMOTE_CONTROL = 791,
	CONTROL_PANEL = 792,
	TWIN_TURBO = 747,
	CALF_SKIN = 748,
	VINO_PRIMO = 749,
	INTEGRALE = 750,
	HAND_BRAKE = 751,
	FADE4 = 752,
	DIRT_DROP = 753,
	RUST_COAT4 = 754,
	SLIDE = 755,
	CONVERTER = 793,
	SWEEPER = 794,
	SAFETY_NET = 795,
	CHECK_ENGINE = 796,
	BRAKE_LIGHT = 797,
	NITRO3 = 798,
	HIGH_BEAM = 799,
	FLEET_FLOCK = 541,
	JUDGEMENT_OF_ANUBIS = 542,
	RED_ASTOR = 543,
	VENTILATORS = 544,
	ORANGE_CRASH = 545,
	FIREFIGHT = 546,
	SPECTRE = 547,
	CHANTICOS_FIRE = 548,
	BIOLEAK = 549,
	OCEANIC = 550,
	ASIIMOV4 = 551,
	FUBAR = 552,
	ATLAS = 553,
	GHOST_CRUSADER = 554,
	RE_ENTRY = 555,
	PRIMAL_SABER = 556,
	BLACK_TIE = 557,
	LORE = 558,
	LORE2 = 559,
	LORE3 = 560,
	LORE4 = 561,
	LORE5 = 562,
	BLACK_LAMINATE2 = 563,
	BLACK_LAMINATE3 = 564,
	BLACK_LAMINATE4 = 565,
	BLACK_LAMINATE5 = 566,
	BLACK_LAMINATE6 = 567,
	GAMMA_DOPPLER = 568,
	GAMMA_DOPPLER2 = 569,
	GAMMA_DOPPLER3 = 570,
	GAMMA_DOPPLER4 = 571,
	GAMMA_DOPPLER5 = 572,
	AUTOTRONIC = 573,
	AUTOTRONIC2 = 574,
	AUTOTRONIC3 = 575,
	AUTOTRONIC4 = 576,
	AUTOTRONIC5 = 577,
	BRIGHT_WATER2 = 578,
	BRIGHT_WATER3 = 579,
	FREEHAND = 580,
	FREEHAND2 = 581,
	FREEHAND3 = 582,
	ARISTOCRAT = 583,
	PHOBOS = 584,
	VIOLENT_DAIMYO = 585,
	WASTELAND_REBEL2 = 586,
	MECHA_INDUSTRIES = 587,
	DESOLATE_SPACE = 588,
	CARNIVORE = 589,
	EXO = 590,
	IMPERIAL_DRAGON = 591,
	IRON_CLAD = 592,
	CHOPPER = 593,
	HARVESTER = 594,
	REBOOT = 595,
	LIMELIGHT = 596,
	BLOODSPORT = 597,
	AERIAL = 598,
	ICE_CAP = 599,
	NEON_REVOLUTION = 600,
	SYD_MEAD = 601,
	IMPRINT = 602,
	DIRECTIVE = 603,
	ROLL_CAGE = 604,
	SCUMBRIA2 = 605,
	VENTILATOR = 606,
	WEASEL = 607,
	PETROGLYPH = 608,
	AIRLOCK = 609,
	DAZZLE = 610,
	GRIM = 611,
	POWERCORE = 612,
	TRIARCH = 613,
	FUEL_INJECTOR2 = 614,
	BRIEFING = 615,
	SLIPSTREAM = 616,
	POLYMER = 622,
	IRONWORK = 623,
	DRAGONFIRE = 624,
	ROYAL_CONSORTS = 625,
	MECHA_INDUSTRIES2 = 626,
	CIRRUS = 627,
	STINGER = 628,
	BLACK_SAND = 629,
	SAND_SCALE = 630,
	FLASHBACK = 631,
	BUZZ_KILL = 632,
	SONAR = 633,
	GILA = 634,
	TURF = 635,
	SHALLOW_GRAVE = 636,
	CYREX4 = 637,
	WASTELAND_PRINCESS = 638,
	BLOODSPORT2 = 639,
	FEVER_DREAM = 640,
	JUNGLE_SLIPSTREAM = 641,
	BLUEPRINT = 642,
	XIANGLIU = 643,
	DECIMATOR = 644,
	OXIDE_BLAZE = 645,
	CAPILLARY = 646,
	CRIMSON_TSUNAMI = 647,
	EMERALD_POISON_DART = 648,
	AKOBEN = 649,
	RIPPLE = 650,
	LAST_DIVE = 651,
	SCAFFOLD = 652,
	NEO_NOIR = 653,
	SEASONS = 654,
	ZANDER = 655,
	ORBIT_MK01 = 656,
	BLUEPRINT2 = 657,
	COBRA_STRIKE = 658,
	MACABRE = 659,
	HYPER_BEAST4 = 660,
	SUGAR_RUSH = 661,
	ONI_TAIJI = 662,
	BRIEFING2 = 663,
	HELLFIRE = 664,
	ALOHA = 665,
	HARD_WATER = 666,
	WOODSMAN = 667,
	RED_ROCK = 668,
	DEATH_GRIP = 669,
	DEATHS_HEAD = 670,
	CUT_OUT = 671,
	METAL_FLOWERS = 672,
	MORRIS = 673,
	TRIQUA = 674,
	THE_EMPRESS = 675,
	HIGH_ROLLER = 676,
	HUNTER = 677,
	SEE_YA_LATER = 678,
	GOO = 679,
	OFF_WORLD = 680,
	LEADED_GLASS = 681,
	OCEANIC2 = 682,
	LLAMA_CANNON = 683,
	CRACKED_OPAL = 684,
	JUNGLE_SLIPSTREAM2 = 685,
	PHANTOM = 686,
	TACTICAT = 687,
	EXPOSURE = 688,
	ZIGGY = 689,
	LAB_RATS = 800,
	STYMPHALIAN = 690,
	MORTIS = 691,
	NIGHT_RIOT = 692,
	FLAME_TEST = 693,
	MOONRISE = 694,
	NEO_NOIR2 = 695,
	BLOODSPORT3 = 696,
	BLACK_SAND2 = 697,
	LIONFISH = 698,
	WILD_SIX = 699,
	URBAN_HAZARD3 = 700,
	GRIP = 701,
	ALOHA2 = 702,
	SWAG_7 = 703,
	ARCTIC_WOLF = 704,
	CORTEX = 705,
	OXIDE_BLAZE2 = 706,
	NEON_RIDER2 = 707,
	AMBER_SLIPSTREAM = 708,
	ECO2 = 709,
	SHRED = 710,
	CODE_RED = 711,
	HIGH_SEAS = 712,
	WARHAWK = 713,
	NIGHTMARE = 714,
	CAPILLARY2 = 715,
	TOY_SOLDIER = 716,
	TRACTION = 717,
	PAW = 718,
	POWERCORE2 = 719,
	DEVOURER = 720,
	SURVIVALIST = 721,
	SNEK_9 = 722,
	EYE_OF_ATHENA = 723,
	NIGHT_STRIPE = 735,
	ASIIMOV5 = 801,
	MOMENTUM = 802,
	NEO_NOIR3 = 803,
	MODEST_THREAT = 804,
	MECHA_INDUSTRIES3 = 805,
	SCAVENGER = 806,
	SIGNAL = 807,
	OXIDE_BLAZE3 = 808,
	WOOD_FIRED = 809,
	PHOSPHOR = 810,
	MAGNESIUM = 811,
	PIPE_DOWN = 812,
	NEVERMORE = 813,
	BLACK_SAND3 = 814,
	DANGER_CLOSE = 815,
	FUBAR2 = 816,
	FLASHBACK2 = 817,
};

int WeaponDefinitions[] = {
	0,
	WEAPON_DEAGLE,
	WEAPON_ELITE,
	WEAPON_FIVESEVEN,
	WEAPON_GLOCK,
	WEAPON_AK47,
	WEAPON_AUG,
	WEAPON_AWP,
	WEAPON_FAMAS,
	WEAPON_G3SG1,
	WEAPON_GALILAR,
	WEAPON_M249,
	WEAPON_M4A1,
	WEAPON_MAC10,
	WEAPON_P90,
	WEAPON_MP5SD,
	WEAPON_UMP45,
	WEAPON_XM1014,
	WEAPON_BIZON,
	WEAPON_MAG7,
	WEAPON_NEGEV,
	WEAPON_SAWEDOFF,
	WEAPON_TEC9,
	WEAPON_HKP2000,
	WEAPON_MP7,
	WEAPON_MP9,
	WEAPON_NOVA,
	WEAPON_P250,
	WEAPON_SCAR20,
	WEAPON_SG556,
	WEAPON_SSG08,
	WEAPON_M4A1_SILENCER,
	WEAPON_USP_SILENCER,
	WEAPON_CZ75A,
	WEAPON_REVOLVER
};
std::string WeaponNames[] = {
	"None",
	"Desert Eagle",
	"Dual Berettas",
	"Five-SeveN",
	"Glock-18",
	"AK-47",
	"AUG",
	"AWP",
	"FAMAS",
	"G3SG1",
	"Galil AR",
	"M249",
	"M4A4",
	"MAC-10",
	"P90",
	"MP5-SD",
	"UMP-45",
	"XM1014",
	"PP-Biton",
	"MAG-7",
	"Negev",
	"Sawed-Off",
	"Tec-9",
	"P2000",
	"MP7",
	"MP9",
	"Nova",
	"P250",
	"SCAR-20",
	"SG 553",
	"SSG 08",
	"M4A1-S",
	"USP-S",
	"CZ75-Auto",
	"R8 Revolver"
};
int PaintKitList[] = {
	DEFAULT,
	GROUNDWATER,
	CANDY_APPLE,
	FOREST_DDPAT,
	ARCTIC_CAMO,
	DESERT_STORM,
	BENGAL_TIGER,
	COPPERHEAD,
	SKULLS,
	CRIMSON_WEB,
	BLUE_STREAK,
	RED_LAMINATE,
	GUNSMOKE,
	JUNGLE_TIGER,
	URBAN_DDPAT,
	VIRUS,
	GRANITE_MARBLEIZED,
	CONTRAST_SPRAY,
	FOREST_LEAVES,
	LICHEN_DASHED,
	BONE_MASK,
	ANODIZED_NAVY,
	SNAKE_CAMO,
	SILVER,
	HOT_ROD,
	METALLIC_DDPAT,
	OSSIFIED,
	BLAZE,
	FADE,
	BULLDOZER,
	NIGHT,
	COPPER,
	BLUE_STEEL,
	STAINED,
	CASE_HARDENED,
	CONTRACTOR,
	COLONY,
	DRAGON_TATTOO,
	LIGHTNING_STRIKE,
	SLAUGHTER,
	DARK_WATER,
	HYPNOTIC,
	BLOOMSTICK,
	COLD_BLOODED,
	CARBON_FIBER,
	SCORPION,
	SAFARI_MESH,
	WINGS,
	POLAR_CAMO,
	BLIZZARD_MARBLEIZED,
	WINTER_FOREST,
	BOREAL_FOREST,
	FOREST_NIGHT,
	ORANGE_DDPAT,
	PINK_DDPAT,
	MUDDER,
	CYANOSPATTER,
	CARAMEL,
	GRASSLAND,
	BLUE_SPRUCE,
	ULTRAVIOLET,
	SAND_DUNE,
	STORM,
	TORNADO,
	WHITEOUT,
	GRASSLAND_LEAVES,
	POLAR_MESH,
	CONDEMNED,
	GLACIER_MESH,
	SAND_MESH,
	SAGE_SPRAY,
	JUNGLE_SPRAY,
	SAND_SPRAY,
	URBAN_PERFORATED,
	WAVES_PERFORATED,
	ORANGE_PEEL,
	URBAN_MASKED,
	JUNGLE_DASHED,
	SAND_DASHED,
	URBAN_DASHED,
	JUNGLE,
	DEMOLITION,
	AFTERIMAGE,
	BULLET_RAIN,
	DEATH_BY_KITTY,
	PALM,
	WALNUT,
	BRASS,
	SPLASH,
	MODERN_HUNTER,
	SPLASH_JAM,
	BLAZE_ORANGE,
	RADIATION_HAZARD,
	NUCLEAR_THREAT,
	FALLOUT_WARNING,
	PREDATOR,
	IRRADIATED_ALERT,
	BLACK_LAMINATE,
	BOOM,
	SCORCHED,
	FADED_ZEBRA,
	MEMENTO,
	DOOMKITTY,
	NUCLEAR_THREAT2,
	FIRE_SERPENT,
	CORTICERA,
	EMERALD_DRAGON,
	OVERGROWTH,
	CORTICERA2,
	GOLDEN_KOI,
	WAVE_SPRAY,
	ZIRKA,
	GRAVEN,
	BRIGHT_WATER,
	BLACK_LIMBA,
	TEMPEST,
	SHATTERED,
	BONE_PILE,
	SPITFIRE,
	DEMETER,
	EMERALD,
	ANODIZED_NAVY2,
	HAZARD,
	DRY_SEASON,
	MAYAN_DREAMS,
	PALM2,
	JUNGLE_DDPAT,
	RUST_COAT,
	MOSAICO,
	JUNGLE2,
	TORNADO2,
	FACETS,
	SAND_DUNE2,
	GROUNDWATER2,
	ANODIZED_GUNMETAL,
	OCEAN_FOAM,
	GRAPHITE,
	OCEAN_FOAM2,
	GRAPHITE2,
	X_RAY,
	BLUE_TITANIUM,
	BLOOD_TIGER,
	HEXANE,
	HIVE,
	HEMOGLOBIN,
	SERUM,
	BLOOD_IN_THE_WATER,
	NIGHTSHADE,
	WATER_SIGIL,
	GHOST_CAMO,
	BLUE_LAMINATE,
	ELECTRIC_HIVE,
	BLIND_SPOT,
	AZURE_ZEBRA,
	STEEL_DISRUPTION,
	COBALT_DISRUPTION,
	CRIMSON_WEB2,
	TROPICAL_STORM,
	ASH_WOOD,
	VARICAMO,
	NIGHT_OPS,
	URBAN_RUBBLE,
	VARICAMO_BLUE,
	CALICAMO,
	HUNTING_BLIND,
	ARMY_MESH,
	GATOR_MESH,
	TEARDOWN,
	ARMY_RECON,
	AMBER_FADE,
	DAMASCUS_STEEL,
	RED_QUARTZ,
	COBALT_QUARTZ,
	FULL_STOP,
	PIT_VIPER,
	SILVER_QUARTZ,
	ACID_FADE,
	NITRO,
	ASIIMOV,
	THE_KRAKEN,
	GUARDIAN,
	MEHNDI,
	REDLINE,
	PULSE,
	MARINA,
	ROSE_IRON,
	RISING_SKULL,
	SANDSTORM,
	KAMI,
	MAGMA,
	COBALT_HALFTONE,
	TREAD_PLATE,
	THE_FUSCHIA_IS_NOW,
	VICTORIA,
	UNDERTOW,
	TITANIUM_BIT,
	HEIRLOOM,
	COPPER_GALAXY,
	RED_FRAGCAM,
	PANTHER,
	STAINLESS,
	BLUE_FISSURE,
	ASIIMOV2,
	CHAMELEON,
	CORPORAL,
	REDLINE2,
	TRIGON,
	HEAT,
	TERRAIN,
	ANTIQUE,
	PULSE2,
	SERGEANT,
	SANDSTORM2,
	GUARDIAN2,
	HEAVEN_GUARD,
	DEATH_RATTLE,
	GREEN_APPLE,
	FRANKLIN,
	METEORITE,
	TUXEDO,
	ARMY_SHEEN,
	CAGED_STEEL,
	EMERALD_PINSTRIPE,
	ATOMIC_ALLOY,
	VULCAN,
	ISAAC,
	SLASHED,
	TORQUE,
	ANTIQUE2,
	RETRIBUTION,
	KAMI2,
	HOWL,
	CURSE,
	DESERT_WARFARE,
	CYREX,
	ORION,
	HEAVEN_GUARD2,
	POISON_DART,
	JAGUAR,
	BRATATAT,
	ROAD_RASH,
	DETOUR,
	RED_PYTHON,
	MASTER_PIECE,
	NITRO2,
	RUST_COAT2,
	CHALICE,
	KNIGHT,
	CHAINMAIL,
	HAND_CANNON,
	DARK_AGE,
	BRIAR,
	ROYAL_BLUE,
	INDIGO,
	TWIST,
	MODULE,
	DESERT_STRIKE,
	TATTER,
	PULSE3,
	CAIMAN,
	JET_SET,
	FIRST_CLASS,
	LEATHER,
	COMMUTER,
	DRAGON_LORE,
	FIRST_CLASS2,
	COACH_CLASS,
	PILOT,
	RED_LEATHER,
	OSIRIS,
	TIGRIS,
	CONSPIRACY,
	FOWL_PLAY,
	WATER_ELEMENTAL,
	URBAN_HAZARD,
	DESERT_STRIKE2,
	KOI,
	IVORY,
	SUPERNOVA,
	ASIIMOV3,
	CYREX2,
	ABYSS,
	LABYRINTH,
	TRAVELER,
	BUSINESS_CLASS,
	OLIVE_PLAID,
	GREEN_PLAID,
	REACTOR,
	SETTING_SUN,
	NUCLEAR_WASTE,
	BONE_MACHINE,
	STYX,
	NUCLEAR_GARDEN,
	CONTAMINATION,
	TOXIC,
	RADIATION_HAZARD2,
	CHEMICAL_GREEN,
	HOT_SHOT,
	FALLOUT_WARNING2,
	CERBERUS,
	WASTELAND_REBEL,
	GRINDER,
	MURKY,
	BASILISK,
	GRIFFIN,
	FIRESTARTER,
	DART,
	URBAN_HAZARD2,
	CARTEL,
	FIRE_ELEMENTAL,
	HIGHWAYMAN,
	CARDIAC,
	DELUSION,
	TRANQUILITY,
	CARTEL2,
	MAN_O_WAR,
	URBAN_SHOCK,
	NAGA,
	CHATTERBOX,
	CATACOMBS,
	DRAGON_KING,
	SYSTEM_LOCK,
	MALACHITE,
	DEADLY_POISON,
	MUERTOS,
	SERENITY,
	GROTTO,
	QUICKSILVER,
	TIGER_TOOTH,
	DAMASCUS_STEEL2,
	DAMASCUS_STEEL3,
	MARBLE_FADE,
	RUST_COAT3,
	DOPPLER,
	DOPPLER2,
	DOPPLER3,
	DOPPLER4,
	DOPPLER5,
	DOPPLER6,
	DOPPLER7,
	ELITE_BUILD,
	ARMOR_CORE,
	WORM_GOD,
	BRONZE_DECO,
	VALENCE,
	MONKEY_BUSINESS,
	ECO,
	DJINN,
	HYPER_BEAST,
	HEAT2,
	MAN_O_WAR2,
	NEON_RIDER,
	ORIGAMI,
	POLE_POSITION,
	GRAND_PRIX,
	TWILIGHT_GALAXY,
	CHRONOS,
	HADES,
	ICARUS_FELL,
	MINOTAURS_LABYRINTH,
	ASTERION,
	PATHFINDER,
	DAEDALUS,
	HOT_ROD2,
	MEDUSA,
	DUELIST,
	PANDORAS_BOX,
	POSEIDON,
	MOON_IN_LIBRA,
	SUN_IN_LEO,
	SHIPPING_FORECAST,
	EMERALD2,
	PARA_GREEN,
	AKIHABARA_ACCEPT,
	HYDROPONIC,
	BAMBOO_PRINT,
	BAMBOO_SHADOW,
	BAMBOO_FOREST,
	AQUA_TERRACE,
	COUNTER_TERRACE,
	TERRACE,
	NEON_KIMONO,
	ORANGE_KIMONO,
	CRIMSON_KIMONO,
	MINT_KIMONO,
	MIDNIGHT_STORM,
	SUNSET_STORM,
	SUNSET_STORM2,
	DAYBREAK,
	IMPACT_DRILL,
	SEABIRD,
	AQUAMARINE_REVENGE,
	HYPER_BEAST2,
	YELLOW_JACKET,
	NEURAL_NET,
	ROCKET_POP,
	BUNSEN_BURNER,
	EVIL_DAIMYO,
	NEMESIS,
	RUBY_POISON_DART,
	LOUDMOUTH,
	RANGER,
	HANDGUN,
	ELITE_BUILD2,
	CYREX3,
	RIOT,
	TORQUE2,
	FRONTSIDE_MISTY,
	DUALING_DRAGONS,
	SURVIVOR_Z,
	FLUX,
	STONE_COLD,
	WRAITHS,
	NEBULA_CRUSADER,
	GOLDEN_COIL,
	RANGEEN,
	COBALT_CORE,
	SPECIAL_DELIVERY,
	WINGSHOT,
	GREEN_MARINE,
	BIG_IRON,
	KILL_CONFIRMED,
	SCUMBRIA,
	POINT_DISARRAY,
	RICOCHET,
	FUEL_ROD,
	CORINTHIAN,
	RETROBUTION,
	THE_EXECUTIONER,
	ROYAL_PALADIN,
	POWER_LOADER,
	IMPERIAL,
	SHAPEWOOD,
	YORICK,
	OUTBREAK,
	TIGER_MOTH,
	AVALANCHE,
	TECLU_BURNER,
	FADE2,
	AMBER_FADE2,
	FUEL_INJECTOR,
	ELITE_BUILD3,
	PHOTIC_ZONE,
	KUMICHO_DRAGON,
	CARTEL3,
	VALENCE2,
	TRIUMVIRATE,
	ROYAL_LEGION,
	THE_BATTLESTAR,
	LAPIS_GATOR,
	PRAETORIAN,
	IMPIRE,
	HYPER_BEAST3,
	NECROPOS,
	JAMBIYA,
	LEAD_CONDUIT,
	DOPPLER8,
	DOPPLER9,
	DOPPLER10,
	ULTRAVIOLET2,
	ULTRAVIOLET3,
	CHARRED,
	SNAKEBITE,
	BRONZED,
	LEATHER2,
	SPRUCE_DDPAT,
	LUNAR_WEAVE,
	CONVOY,
	CRIMSON_WEAVE,
	SUPERCONDUCTOR,
	ARID,
	SLAUGHTER2,
	ECLIPSE,
	SPEARMINT,
	BOOM2,
	COOL_MINT,
	FOREST_DDPAT2,
	CRIMSON_KIMONO2,
	EMERALD_WEB,
	FOUNDATION,
	BADLANDS,
	PANDORAS_BOX2,
	HEDGE_MAZE,
	GUERRILLA,
	DIAMONDBACK,
	KING_SNAKE,
	IMPERIAL_PLAID,
	OVERTAKE,
	RACING_GREEN,
	AMPHIBIOUS,
	BRONZE_MORPH,
	OMEGA,
	VICE,
	POW,
	TURTLE,
	TRANSPORT,
	POLYGON,
	COBALT_SKULLS,
	OVERPRINT,
	DUCT_TAPE,
	ARBOREAL,
	EMERALD3,
	MANGROVE,
	RATTLER,
	CASE_HARDENED2,
	CRIMSON_WEB3,
	BUCKSHOT,
	FADE3,
	MOGUL,
	FACILITY_SKETCH,
	FACILITY_NEGATIVE,
	FACILITY_DRAFT,
	FACILITY_DARK,
	RANDOM_ACCESS,
	MAINFRAME,
	CO_PROCESSOR,
	MOTHERBOARD,
	BULKHEAD,
	COOLANT,
	MANDREL,
	EXCHANGER,
	CORE_BREACH,
	ACHERON,
	NUCLEAR_GARDEN3,
	COLD_FUSION,
	REMOTE_CONTROL,
	CONTROL_PANEL,
	TWIN_TURBO,
	CALF_SKIN,
	VINO_PRIMO,
	INTEGRALE,
	HAND_BRAKE,
	FADE4,
	DIRT_DROP,
	RUST_COAT4,
	SLIDE,
	CONVERTER,
	SWEEPER,
	SAFETY_NET,
	CHECK_ENGINE,
	BRAKE_LIGHT,
	NITRO3,
	HIGH_BEAM,
	FLEET_FLOCK,
	JUDGEMENT_OF_ANUBIS,
	RED_ASTOR,
	VENTILATORS,
	ORANGE_CRASH,
	FIREFIGHT,
	SPECTRE,
	CHANTICOS_FIRE,
	BIOLEAK,
	OCEANIC,
	ASIIMOV4,
	FUBAR,
	ATLAS,
	GHOST_CRUSADER,
	RE_ENTRY,
	PRIMAL_SABER,
	BLACK_TIE,
	LORE,
	LORE2,
	LORE3,
	LORE4,
	LORE5,
	BLACK_LAMINATE2,
	BLACK_LAMINATE3,
	BLACK_LAMINATE4,
	BLACK_LAMINATE5,
	BLACK_LAMINATE6,
	GAMMA_DOPPLER,
	GAMMA_DOPPLER2,
	GAMMA_DOPPLER3,
	GAMMA_DOPPLER4,
	GAMMA_DOPPLER5,
	AUTOTRONIC,
	AUTOTRONIC2,
	AUTOTRONIC3,
	AUTOTRONIC4,
	AUTOTRONIC5,
	BRIGHT_WATER2,
	BRIGHT_WATER3,
	FREEHAND,
	FREEHAND2,
	FREEHAND3,
	ARISTOCRAT,
	PHOBOS,
	VIOLENT_DAIMYO,
	WASTELAND_REBEL2,
	MECHA_INDUSTRIES,
	DESOLATE_SPACE,
	CARNIVORE,
	EXO,
	IMPERIAL_DRAGON,
	IRON_CLAD,
	CHOPPER,
	HARVESTER,
	REBOOT,
	LIMELIGHT,
	BLOODSPORT,
	AERIAL,
	ICE_CAP,
	NEON_REVOLUTION,
	SYD_MEAD,
	IMPRINT,
	DIRECTIVE,
	ROLL_CAGE,
	SCUMBRIA2,
	VENTILATOR,
	WEASEL,
	PETROGLYPH,
	AIRLOCK,
	DAZZLE,
	GRIM,
	POWERCORE,
	TRIARCH,
	FUEL_INJECTOR2,
	BRIEFING,
	SLIPSTREAM,
	POLYMER,
	IRONWORK,
	DRAGONFIRE,
	ROYAL_CONSORTS,
	MECHA_INDUSTRIES2,
	CIRRUS,
	STINGER,
	BLACK_SAND,
	SAND_SCALE,
	FLASHBACK,
	BUZZ_KILL,
	SONAR,
	GILA,
	TURF,
	SHALLOW_GRAVE,
	CYREX4,
	WASTELAND_PRINCESS,
	BLOODSPORT2,
	FEVER_DREAM,
	JUNGLE_SLIPSTREAM,
	BLUEPRINT,
	XIANGLIU,
	DECIMATOR,
	OXIDE_BLAZE,
	CAPILLARY,
	CRIMSON_TSUNAMI,
	EMERALD_POISON_DART,
	AKOBEN,
	RIPPLE,
	LAST_DIVE,
	SCAFFOLD,
	NEO_NOIR,
	SEASONS,
	ZANDER,
	ORBIT_MK01,
	BLUEPRINT2,
	COBRA_STRIKE,
	MACABRE,
	HYPER_BEAST4,
	SUGAR_RUSH,
	ONI_TAIJI,
	BRIEFING2,
	HELLFIRE,
	ALOHA,
	HARD_WATER,
	WOODSMAN,
	RED_ROCK,
	DEATH_GRIP,
	DEATHS_HEAD,
	CUT_OUT,
	METAL_FLOWERS,
	MORRIS,
	TRIQUA,
	THE_EMPRESS,
	HIGH_ROLLER,
	HUNTER,
	SEE_YA_LATER,
	GOO,
	OFF_WORLD,
	LEADED_GLASS,
	OCEANIC2,
	LLAMA_CANNON,
	CRACKED_OPAL,
	JUNGLE_SLIPSTREAM2,
	PHANTOM,
	TACTICAT,
	EXPOSURE,
	ZIGGY,
	LAB_RATS,
	STYMPHALIAN,
	MORTIS,
	NIGHT_RIOT,
	FLAME_TEST,
	MOONRISE,
	NEO_NOIR2,
	BLOODSPORT3,
	BLACK_SAND2,
	LIONFISH,
	WILD_SIX,
	URBAN_HAZARD3,
	GRIP,
	ALOHA2,
	SWAG_7,
	ARCTIC_WOLF,
	CORTEX,
	OXIDE_BLAZE2,
	NEON_RIDER2,
	AMBER_SLIPSTREAM,
	ECO2,
	SHRED,
	CODE_RED,
	HIGH_SEAS,
	WARHAWK,
	NIGHTMARE,
	CAPILLARY2,
	TOY_SOLDIER,
	TRACTION,
	PAW,
	POWERCORE2,
	DEVOURER,
	SURVIVALIST,
	SNEK_9,
	EYE_OF_ATHENA,
	NIGHT_STRIPE,
	ASIIMOV5,
	MOMENTUM,
	NEO_NOIR3,
	MODEST_THREAT,
	MECHA_INDUSTRIES3,
	SCAVENGER,
	SIGNAL,
	OXIDE_BLAZE3,
	WOOD_FIRED,
	PHOSPHOR,
	MAGNESIUM,
	PIPE_DOWN,
	NEVERMORE,
	BLACK_SAND3,
	DANGER_CLOSE,
	FUBAR2,
	FLASHBACK2
};
std::string PaintKitNames[] = {
	"Default",
	"Groundwater",
	"Candy Apple",
	"Forest DDPAT",
	"Arctic Camo",
	"Desert Storm",
	"Bengal Tiger",
	"Copperhead",
	"Skulls",
	"Crimson Web",
	"Blue Streak",
	"Red Laminate",
	"Gunsmoke",
	"Jungle Tiger",
	"Urban DDPAT",
	"Virus",
	"Granite Marbleized",
	"Contrast Spray",
	"Forest Leaves",
	"Lichen Dashed",
	"Bone Mask",
	"Anodized Navy",
	"Snake Camo",
	"Silver",
	"Hot Rod",
	"Metallic DDPAT",
	"Ossified",
	"Blaze",
	"Fade",
	"Bulldozer",
	"Night",
	"Copper",
	"Blue Steel",
	"Stained",
	"Case Hardened",
	"Contractor",
	"Colony",
	"Dragon Tattoo",
	"Lightning Strike",
	"Slaughter",
	"Dark Water",
	"Hypnotic",
	"Bloomstick",
	"Cold Blooded",
	"Carbon Fiber",
	"Scorpion",
	"Safari Mesh",
	"Wings",
	"Polar Camo",
	"Blizzard Marbleized",
	"Winter Forest",
	"Boreal Forest",
	"Forest Night",
	"Orange DDPAT",
	"Pink DDPAT",
	"Mudder",
	"Cyanospatter",
	"Caramel",
	"Grassland",
	"Blue Spruce",
	"Ultraviolet",
	"Sand Dune",
	"Storm",
	"Tornado",
	"Whiteout",
	"Grassland Leaves",
	"Polar Mesh",
	"Condemned",
	"Glacier Mesh",
	"Sand Mesh",
	"Sage Spray",
	"Jungle Spray",
	"Sand Spray",
	"Urban Perforated",
	"Waves Perforated",
	"Orange Peel",
	"Urban Masked",
	"Jungle Dashed",
	"Sand Dashed",
	"Urban Dashed",
	"Jungle",
	"Demolition",
	"Afterimage",
	"Bullet Rain",
	"Death by Kitty",
	"Palm",
	"Walnut",
	"Brass",
	"Splash",
	"Modern Hunter",
	"Splash Jam",
	"Blaze Orange",
	"Radiation Hazard",
	"Nuclear Threat",
	"Fallout Warning",
	"Predator",
	"Irradiated Alert",
	"Black Laminate",
	"Boom!",
	"Scorched",
	"Faded Zebra",
	"Memento",
	"Doomkitty",
	"Nuclear Threat",
	"Fire Serpent",
	"Corticera",
	"Emerald Dragon",
	"Overgrowth",
	"Corticera",
	"Golden Koi",
	"Wave Spray",
	"Zirka",
	"Graven",
	"Bright Water",
	"Black Limba",
	"Tempest",
	"Shattered",
	"Bone Pile",
	"Spitfire",
	"Demeter",
	"Emerald",
	"Anodized Navy",
	"Hazard",
	"Dry Season",
	"Mayan Dreams",
	"Palm",
	"Jungle DDPAT",
	"Rust Coat",
	"Mosaico",
	"Jungle",
	"Tornado",
	"Facets",
	"Sand Dune",
	"Groundwater",
	"Anodized Gunmetal",
	"Ocean Foam",
	"Graphite",
	"Ocean Foam",
	"Graphite",
	"X Ray",
	"Blue Titanium",
	"Blood Tiger",
	"Hexane",
	"Hive",
	"Hemoglobin",
	"Serum",
	"Blood In The Water",
	"Nightshade",
	"Water Sigil",
	"Ghost Camo",
	"Blue Laminate",
	"Electric Hive",
	"Blind Spot",
	"Azure Zebra",
	"Steel Disruption",
	"Cobalt Disruption",
	"Crimson Web",
	"Tropical Storm",
	"Ash Wood",
	"VariCamo",
	"Night Ops",
	"Urban Rubble",
	"VariCamo Blue",
	"CaliCamo",
	"Hunting Blind",
	"Army Mesh",
	"Gator Mesh",
	"Teardown",
	"Army Recon",
	"Amber Fade",
	"Damascus Steel",
	"Red Quartz",
	"Cobalt Quartz",
	"Full Stop",
	"Pit Viper",
	"Silver Quartz",
	"Acid Fade",
	"Nitro",
	"Asiimov",
	"The Kraken",
	"Guardian",
	"Mehndi",
	"Redline",
	"Pulse",
	"Marina",
	"Rose Iron",
	"Rising Skull",
	"Sandstorm",
	"Kami",
	"Magma",
	"Cobalt Halftone",
	"Tread Plate",
	"The Fuschia Is Now",
	"Victoria",
	"Undertow",
	"Titanium Bit",
	"Heirloom",
	"Copper Galaxy",
	"Red FragCam",
	"Panther",
	"Stainless",
	"Blue Fissure",
	"Asiimov",
	"Chameleon",
	"Corporal",
	"Redline",
	"Trigon",
	"Heat",
	"Terrain",
	"Antique",
	"Pulse",
	"Sergeant",
	"Sandstorm",
	"Guardian",
	"Heaven Guard",
	"Death Rattle",
	"Green Apple",
	"Franklin",
	"Meteorite",
	"Tuxedo",
	"Army Sheen",
	"Caged Steel",
	"Emerald Pinstripe",
	"Atomic Alloy",
	"Vulcan",
	"Isaac",
	"Slashed",
	"Torque",
	"Antique",
	"Retribution",
	"Kami",
	"Howl",
	"Curse",
	"Desert Warfare",
	"Cyrex",
	"Orion",
	"Heaven Guard",
	"Poison Dart",
	"Jaguar",
	"Bratatat",
	"Road Rash",
	"Detour",
	"Red Python",
	"Master Piece",
	"Nitro",
	"Rust Coat",
	"Chalice",
	"Knight",
	"Chainmail",
	"Hand Cannon",
	"Dark Age",
	"Briar",
	"Royal Blue",
	"Indigo",
	"Twist",
	"Module",
	"Desert Strike",
	"Tatter",
	"Pulse",
	"Caiman",
	"Jet Set",
	"First Class",
	"Leather",
	"Commuter",
	"Dragon Lore",
	"First Class",
	"Coach Class",
	"Pilot",
	"Red Leather",
	"Osiris",
	"Tigris",
	"Conspiracy",
	"Fowl Play",
	"Water Elemental",
	"Urban Hazard",
	"Desert Strike",
	"Koi",
	"Ivory",
	"Supernova",
	"Asiimov",
	"Cyrex",
	"Abyss",
	"Labyrinth",
	"Traveler",
	"Business Class",
	"Olive Plaid",
	"Green Plaid",
	"Reactor",
	"Setting Sun",
	"Nuclear Waste",
	"Bone Machine",
	"Styx",
	"Nuclear Garden",
	"Contamination",
	"Toxic",
	"Radiation Hazard",
	"Chemical Green",
	"Hot Shot",
	"Fallout Warning",
	"Cerberus",
	"Wasteland Rebel",
	"Grinder",
	"Murky",
	"Basilisk",
	"Griffin",
	"Firestarter",
	"Dart",
	"Urban Hazard",
	"Cartel",
	"Fire Elemental",
	"Highwayman",
	"Cardiac",
	"Delusion",
	"Tranquility",
	"Cartel",
	"Man O War",
	"Urban Shock",
	"Naga",
	"Chatterbox",
	"Catacombs",
	"Dragon King",
	"System Lock",
	"Malachite",
	"Deadly Poison",
	"Muertos",
	"Serenity",
	"Grotto",
	"Quicksilver",
	"Tiger Tooth",
	"Damascus Steel",
	"Damascus Steel",
	"Marble Fade",
	"Rust Coat",
	"Doppler (Ruby)",
	"Doppler (Sapphire)",
	"Doppler (Black Pearl)",
	"Doppler (Phase 1)",
	"Doppler (Phase 2)",
	"Doppler (Phase 3)",
	"Doppler (Phase 4)",
	"Elite Build",
	"Armor Core",
	"Worm God",
	"Bronze Deco",
	"Valence",
	"Monkey Business",
	"Eco",
	"Djinn",
	"Hyper Beast",
	"Heat",
	"Man O War",
	"Neon Rider",
	"Origami",
	"Pole Position",
	"Grand Prix",
	"Twilight Galaxy",
	"Chronos",
	"Hades",
	"Icarus Fell",
	"Minotaurs Labyrinth",
	"Asterion",
	"Pathfinder",
	"Daedalus",
	"Hot Rod",
	"Medusa",
	"Duelist",
	"Pandoras Box",
	"Poseidon",
	"Moon In Libra",
	"Sun In Leo",
	"Shipping Forecast",
	"Emerald",
	"Para Green",
	"Akihabara Accept",
	"Hydroponic",
	"Bamboo Print",
	"Bamboo Shadow",
	"Bamboo Forest",
	"Aqua Terrace",
	"Counter Terrace",
	"Terrace",
	"Neon Kimono",
	"Orange Kimono",
	"Crimson Kimono",
	"Mint Kimono",
	"Midnight Storm",
	"Sunset Storm",
	"Sunset Storm",
	"Daybreak",
	"Impact Drill",
	"Seabird",
	"Aquamarine Revenge",
	"Hyper Beast",
	"Yellow Jacket",
	"Neural Net",
	"Rocket Pop",
	"Bunsen Burner",
	"Evil Daimyo",
	"Nemesis",
	"Ruby Poison Dart",
	"Loudmouth",
	"Ranger",
	"Handgun",
	"Elite Build",
	"Cyrex",
	"Riot",
	"Torque",
	"Frontside Misty",
	"Dualing Dragons",
	"Survivor Z",
	"Flux",
	"Stone Cold",
	"Wraiths",
	"Nebula Crusader",
	"Golden Coil",
	"Rangeen",
	"Cobalt Core",
	"Special Delivery",
	"Wingshot",
	"Green Marine",
	"Big Iron",
	"Kill Confirmed",
	"Scumbria",
	"Point Disarray",
	"Ricochet",
	"Fuel Rod",
	"Corinthian",
	"Retrobution",
	"The Executioner",
	"Royal Paladin",
	"Power Loader",
	"Imperial",
	"Shapewood",
	"Yorick",
	"Outbreak",
	"Tiger Moth",
	"Avalanche",
	"Teclu Burner",
	"Fade",
	"Amber Fade",
	"Fuel Injector",
	"Elite Build",
	"Photic Zone",
	"Kumicho Dragon",
	"Cartel",
	"Valence",
	"Triumvirate",
	"Royal Legion",
	"The Battlestar",
	"Lapis Gator",
	"Praetorian",
	"Impire",
	"Hyper Beast",
	"Necropos",
	"Jambiya",
	"Lead Conduit",
	"Doppler8",
	"Doppler9",
	"Doppler",
	"Ultraviolet",
	"Ultraviolet",
	"Charred",
	"Snakebite",
	"Bronzed",
	"Leather",
	"Spruce Ddpat",
	"Lunar Weave",
	"Convoy",
	"Crimson Weave",
	"Superconductor",
	"Arid",
	"Slaughter",
	"Eclipse",
	"Spearmint",
	"Boom",
	"Cool Mint",
	"Forest Ddpat",
	"Crimson Kimono",
	"Emerald Web",
	"Foundation",
	"Badlands",
	"Pandoras Box",
	"Hedge Maze",
	"Guerrilla",
	"Diamondback",
	"King Snake",
	"Imperial Plaid",
	"Overtake",
	"Racing Green",
	"Amphibious",
	"Bronze Morph",
	"Omega",
	"Vice",
	"Pow",
	"Turtle",
	"Transport",
	"Polygon",
	"Cobalt Skulls",
	"Overprint",
	"Duct Tape",
	"Arboreal",
	"Emerald",
	"Mangrove",
	"Rattler",
	"Case Hardened",
	"Crimson Web",
	"Buckshot",
	"Fade",
	"Mogul",
	"Facility Sketch",
	"Facility Negative",
	"Facility Draft",
	"Facility Dark",
	"Random Access",
	"Mainframe",
	"Co Processor",
	"Motherboard",
	"Bulkhead",
	"Coolant",
	"Mandrel",
	"Exchanger",
	"Core Breach",
	"Acheron",
	"Nuclear Garden",
	"Cold Fusion",
	"Remote Control",
	"Control Panel",
	"Twin Turbo",
	"Calf Skin",
	"Vino Primo",
	"Integrale",
	"Hand Brake",
	"Fade",
	"Dirt Drop",
	"Rust Coat",
	"Slide",
	"Converter",
	"Sweeper",
	"Safety Net",
	"Check Engine",
	"Brake Light",
	"Nitro",
	"High Beam",
	"Fleet Flock",
	"Judgement Of Anubis",
	"Red Astor",
	"Ventilators",
	"Orange Crash",
	"Firefight",
	"Spectre",
	"Chantico's Fire",
	"Bioleak",
	"Oceanic",
	"Asiimov",
	"Fubar",
	"Atlas",
	"Ghost Crusader",
	"Re-Entry",
	"Primal Saber",
	"Black Tie",
	"Lore",
	"Lore",
	"Lore",
	"Lore",
	"Lore",
	"Black Laminate",
	"Black Laminate",
	"Black Laminate",
	"Black Laminate",
	"Black Laminate",
	"Gamma Doppler (Emerald)",
	"Gamma Doppler (Phase 1)",
	"Gamma Doppler (Phase 2)",
	"Gamma Doppler (Phase 3)",
	"Gamma Doppler (Phase 4)",
	"Autotronic",
	"Autotronic",
	"Autotronic",
	"Autotronic",
	"Autotronic",
	"Bright Water",
	"Bright Water",
	"Freehand",
	"Freehand",
	"Freehand",
	"Aristocrat",
	"Phobos",
	"Violent Daimyo",
	"Wasteland Rebel",
	"Mecha Industries",
	"Desolate Space",
	"Carnivore",
	"Exo",
	"Imperial Dragon",
	"Iron Clad",
	"Chopper",
	"Harvester",
	"Reboot",
	"Limelight",
	"Bloodsport",
	"Aerial",
	"Ice Cap",
	"Neon Revolution",
	"Syd Mead",
	"Imprint",
	"Directive",
	"Roll Cage",
	"Scumbria",
	"Ventilator",
	"Weasel",
	"Petroglyph",
	"Airlock",
	"Dazzle",
	"Grim",
	"Powercore",
	"Triarch",
	"Fuel Injector",
	"Briefing",
	"Slipstream",
	"Polymer",
	"Ironwork",
	"Dragonfire",
	"Royal Consorts",
	"Mecha Industries",
	"Cirrus",
	"Stinger",
	"Black Sand",
	"Sand Scale",
	"Flashback",
	"Buzz Kill",
	"Sonar",
	"Gila",
	"Turf",
	"Shallow Grave",
	"Cyrex",
	"Wasteland Princess",
	"Bloodsport",
	"Fever Dream",
	"Jungle Slipstream",
	"Blueprint",
	"Xiangliu",
	"Decimator",
	"Oxide Blaze",
	"Capillary",
	"Crimson Tsunami",
	"Emerald Poison Dart",
	"Akoben",
	"Ripple",
	"Last Dive",
	"Scaffold",
	"Neo-Noir",
	"Seasons",
	"Zander",
	"Orbit Mk",
	"Blueprint",
	"Cobra Strike",
	"Macabre",
	"Hyper Beast",
	"Sugar Rush",
	"Oni Taiji",
	"Briefing",
	"Hellfire",
	"Aloha",
	"Hard Water",
	"Woodsman",
	"Red Rock",
	"Death Grip",
	"Death's Head",
	"Cut Out",
	"Metal Flowers",
	"Morris",
	"Triqua",
	"The Empress",
	"High Roller",
	"Hunter",
	"See Ya Later",
	"Goo",
	"Off World",
	"Leaded Glass",
	"Oceanic",
	"Llama Cannon",
	"Cracked Opal",
	"Jungle Slipstream",
	"Phantom",
	"Tacticat",
	"Exposure",
	"Ziggy",
	"Lab Rats",
	"Stymphalian",
	"Mortis",
	"Night Riot",
	"Flame Test",
	"Moonrise",
	"Neo-Noir",
	"Bloodsport",
	"Black Sand",
	"Lionfish",
	"Wild Six",
	"Urban Hazard",
	"Grip",
	"Aloha",
	"Swag 7",
	"Arctic Wolf",
	"Cortex",
	"Oxide Blaze",
	"Neon Rider",
	"Amber Slipstream",
	"Eco",
	"Shred",
	"Code Red",
	"High Seas",
	"Warhawk",
	"Nightmare",
	"Capillary",
	"Toy Soldier",
	"Traction",
	"Paw",
	"Powercore",
	"Devourer",
	"Survivalist",
	"Snek-9",
	"Eye Of Athena",
	"Night Stripe",
	"Asiimov",
	"Momentum",
	"Neo-Noir",
	"Modest Threat",
	"Mecha Industries",
	"Scavenger",
	"Signal",
	"Oxide Blaze",
	"Wood Fired",
	"Phosphor",
	"Magnesium",
	"Pipe Down",
	"Nevermore",
	"Black Sand",
	"Danger Close",
	"Fubar",
	"Flashback"
};

struct WeaponSkinList_t {
	void Init(int num, ...) {
		va_list args;
		va_start(args, num);
		for (int i = 0; i <= num; i++) {
			List[i] = va_arg(args, int);
		}
		va_end(args);
		Size = num;
	}
	int List[255] = { 0 };
	int Size = 0;
};

namespace Settings {
	namespace Rage {
		/* ANTI AIM */
		bool bAntiaim = false;
		AntiAimType_t antiAimType = ANTIAIM_NONE;
		/* SILENT AIM */
		bool bSilentAim;
	}
	namespace Visuals{
		/* CHAMS */
		bool bChamsEnabled = true;
		int chamsMaterial = MATERIAL_NONE;
		bool bChamsEnemiesNormal = false;
		bool bChamsEnemiesIgnoreZ = false;
		bool bChamsAlliesNormal = false;
		bool bChamsAlliesIgnoreZ = false;
		bool bChamsHandChamsEnabled = false;
		bool bChamsWeaponChamsEnabled = false;


		float chamsEnemiesNormalR = 193.0f;
		float chamsEnemiesNormalG = 30.0f;
		float chamsEnemiesNormalB = 54.0f;
		float chamsEnemiesIgnoreZR = 0.0f;
		float chamsEnemiesIgnoreZG = 179.0f;
		float chamsEnemiesIgnoreZB = 235.0f;

		float chamsAlliesNormalR = 46.0f;
		float chamsAlliesNormalG = 204.0f;
		float chamsAlliesNormalB = 113.0f;
		float chamsAlliesIgnoreZR = 16.0f;
		float chamsAlliesIgnoreZG = 109.0f;
		float chamsAlliesIgnoreZB = 90.0f;

		float chamsHandChamsR = 235.0f;
		float chamsHandChamsG = 254.0f;
		float chamsHandChamsB = 3.0f;

		float chamsWeaponChamsR = 235.0f;
		float chamsWeaponChamsG = 254.0f;
		float chamsWeaponChamsB = 3.0f;

		/* GLOW */
		bool bGlowEnabled = false;
		bool bGlowOnlyEnemies = false;
		bool bGlowIgnoreZ = false;
		float glowEnemiesIgnoreZR = 0.0f;
		float glowEnemiesIgnoreZG = 0.0f;
		float glowEnemiesIgnoreZB = 0.0f;
		float glowEnemiesNormalR = 0.0f;
		float glowEnemiesNormalG = 0.0f;
		float glowEnemiesNormalB = 0.0f;
		float glowAllyR = 0.0f;
		float glowAllyG = 0.0f;
		float glowAllyB = 0.0f;

		/* ESP */
		bool bEspEnabled = false;
		int espBoxType = ESPBOX_NONE;
		bool bESPEnemiesNormal = false;
		float espEnemiesNormalR = 255.0f;
		float espEnemiesNormalG = 255.0f;
		float espEnemiesNormalB = 255.0f;
		bool bESPEnemiesIgnoreZ = false;
		float espEnemiesIgnoreZR = 193.0f;
		float espEnemiesIgnoreZG = 30.0f;
		float espEnemiesIgnoreZB = 54.0f;
		bool bESPAlliesNormal = false;
		float espAlliesNormalR = 193.0f;
		float espAlliesNormalG = 30.0f;
		float espAlliesNormalB = 54.0f;
		bool bESPAlliesIgnoreZ = false;
		float espAlliesIgnoreZR = 193.0f;
		float espAlliesIgnoreZG = 30.0f;
		float espAlliesIgnoreZB = 54.0f;
		bool bESPBone = false;
		bool bESPName = false;
		bool bESPHealth = false;
		int espHealtBar = HEALTHBAR_NONE;
		bool bESPWeapon = false;

		/* GRENADE TRAJECTORY */
		bool bGrenadeTrajectoryEnabled = false;
		bool bGrenadeTrajectoryShowDamage = false;
		float grenadeTrajectoryR = 255.0f;
		float grenadeTrajectoryG = 255.0f;
		float grenadeTrajectoryB = 255.0f;
	}
	namespace SkinChanger {
		/* KNIFE CHANGER */
		bool bKnifeChangerEnabled = false;
		int Knife = 0;
		int KnifeSkin = 0;
		float KnifeWear = 0.0f;
		bool bKnifeStattrak = false;
		int KnifeStattrak = 0;

		/* GLOVE CHANGER */
		bool bGloveChangerEnabled = true;
		int Glove = 1;
		int GloveSkin = 0;

		/* SKIN CHANGER */
		bool bSkinChangerEnabled = false;
		int CurrentWeapon = 0;
		int WeaponSkin;
		float WeaponWear;
		bool bWeaponStattrak;
		int WeaponStattrak;

		int WeaponSkins[255] = { 0 };
		float WeaponWears[255] = { 0 };
		bool bWeaponStattraks[255] = { 0 };
		int WeaponStattraks[255] = { 0 };

		int KnifeModelSkin = 0;
	}
	namespace Misc {
		/* THIRDPERSON */
		bool bThirdpersonEnabled = false;
		bool bThirdperson = true;
		float ThirdpersonDistance = 5.0f;
		short ThirdpersonToggleKey = VK_MENU;

		/* BUNNYHOP & AUTOSTRAFE */
		bool bBunnyhop = false;
		short BunnyhopKey = VK_SPACE;

		/* CONFIG */
		int SelectedConfig = 0;

		/* NIGHTMODE */
		bool bNightmodeEnabled = false;

		/* CLAN TAG CHANGER */
		bool bClanTagChangerEnabled = false;
	}
}

QAngle oldViewAngles;
float antiAimX = 0.0f;
float antiAimY = 0.0f;
float antiAimZ = 0.0f;
QAngle silentAimViewAngles;
matrix3x4_t antiAimBones[128];

#endif