#ifndef SDK_H
#define SDK_H

#include "math/mathlib.h"
#include "basetypes.h"
#include "C_BaseCombatWeapon.h"
#include "C_BaseEntity.h"
#include "C_BasePlayer.h"
#include "CInput.h"
#include "Color.h"
#include "ConVar.h"
#include "CViewSetup.h"
#include "CUserCmd.h"
#include "IAppSystem.h"
#include "IClientEntity.h"
#include "IClientEntityList.h"
#include "IClientNetworkable.h"
#include "IClientPanel.h"
#include "IClientRenderable.h"
#include "IClientThinkable.h"
#include "IHTML.h"
#include "IImage.h"
#include "IInput.h"
#include "ImageFormat.h"
#include "IMaterial.h"
#include "IMaterialSystem.h"
#include "Interface.h"
#include "IPanel.h"
#include "ISurface.h"
#include "IVEngineClient.h"
#include "IVModelRender.h"

#endif